config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'blogs#index'

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :blogs, only: [:index, :new, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password

	has_many :blogs, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authenticate_user
    if current_user.nil?
      redirect_to new_session_path, alert: 'Please log in'
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user

  def index
    @blogs = current_user.blogs
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = current_user.blogs.new(blog_params)

    if @blog.save
      redirect_to root_path, notice: 'Blog created successfully'
    else
      render :new
    end
  end

  private

  def blog_params
    params.require(:blog).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new; end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Login successful'
    else
      flash[:alert] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logout successful'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new; end

  def create
    user = User.new(user_params)

    if user.save
      session[:user_id] = user.id
      redirect_to root_path, notice: 'User created successfully'
    else
      flash[:alert] = user.errors.full_messages.join(', ')
      render :new
    end
  end

  private

  def user_params
    params.permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
<h1>My Blogs</h1>

<%= link_to 'Write a New Blog', new_blog_path %>
<% if @blogs.any? %>
  <ul>
    <% @blogs.each do |blog| %>
      <li>
        <strong><%= blog.title %></strong>
        <p><%= blog.content %></p>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>You haven't written any blogs yet. <%= link_to 'Write one now!', new_blog_path %></p>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= link_to 'Back to Blogs', blogs_path %>

<%= form_with(model: @blog, url: blogs_path, method: :post) do |form| %>
	<div>
	  <%= form.label :title %>
	  <%= form.text_field :title %>
	</div>

	<div>
	  <%= form.label :content %>
	  <%= form.text_area :content %>
	</div>

	<div>
	  <%= form.submit 'Create Blog' %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <% if session[:user_id] %>
    
      <% flash.each do |key, message| %>
        <div class="<%= key %>">
          <%= message %>
        </div>
      <% end %>

      <p>Welcome, <%= current_user.email %></p>
      <%= button_to 'Logout', session_path(current_user), method: :delete %>
    <% else %>
      <%= link_to 'Sign Up', new_user_path %> |
      <%= link_to 'Sign In', new_session_path %>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with(model: @user, url: users_path, method: :post) do |form| %>

	<% flash.each do |key, message| %>
    <div class="<%= key %>">
      <%= message %>
    </div>
  <% end %>
	
	<div>
	  <%= form.label :email %>
	  <%= form.email_field :email %>
	</div>

	<div>
	  <%= form.label :name %>
	  <%= form.text_field :name %>
	</div>

	<div>
	  <%= form.label :password %>
	  <%= form.password_field :password %>
	</div>

	<div>
	  <%= form.label :password_confirmation %>
	  <%= form.password_field :password_confirmation %>
	</div>

	<div>
	  <%= form.submit 'Sign Up' %>
	</div>
<% end %>